# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true

# Mod Properties
mod_id=pixelmonlegendslevelled
mod_name=Pixelmon Legends Levelled
mod_version=9.3.16.x.1
mod_group_id=com.pixelmonlegendslevelled
mod_authors=CCDelic
mod_description=Legendaries and Ultra Beasts always spawn at the level of the nearest player's strongest party Pokemon.
mod_license=MIT

# NeoForge
neo_version=21.1.172
loader_version_range=[1,)
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependencies
pixelmon_version=9.3.16
